name: Run Automation Test Framework

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: maven:3.8.6-openjdk-8  # Menggunakan Docker image Maven dengan JDK 8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run API Tests
        run: ./gradlew test -Ptags=api

      - name: Run Web UI Tests
        run: ./gradlew test -Ptags=web

      - name: Upload API Test Report
        uses: actions/upload-artifact@v3
        with:
          name: api-test-report
          path: build/reports/tests/api/

      - name: Upload Web UI Test Report
        uses: actions/upload-artifact@v3
        with:
          name: web-test-report
          path: build/reports/tests/web/