name: Debugging Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Verify Project Structure
        run: ls -R src/test/java

      - name: Check Gradle Version
          run: ./gradlew --version

      - name: Clear Gradle Cache
          run: rm -rf ~/.gradle/caches ~/.gradle/wrapper

      - name: Run All Tests
        run: ./gradlew clean test --info

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests